client_config_backend: settings
client_config:
  client_id: 212238864030-qlq7baq94llpi2oimm6oeonbvouhgv62.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: ./config/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive